---
title: "Pixel Sampling"
author: "Joseph Bolton"
date: "07 December 2019"    
output:
  html_document:
    df_print: paged
    theme: darkly
---

```{r}
library(imager)
library(tidyverse)

# change formatting of code output:
knitr::opts_chunk$set(
  class.output  = "bg-primary",
  class.message = "bg-info text-info",
  class.warning = "bg-warning text-warning",
  class.error   = "bg-danger text-danger"
)
```

```{r}
load_image <- 
  imager::load.image("C:/Users/Joe Bolton/Desktop/sync_to_google_drive/finished_blogs/my_face_raw_img.jpg") %>% 
  imager::grayscale()
```

```{r}
dim(load_image)
```

```{r}
plot(load_image)
```

```{r fig.width=12}
load_image %>% 
  as.data.frame() %>% 
  as_tibble() %>% 
  mutate( value = 1 - ( value-min(value) ) / ( max(value)-min(value) ) ) %>% 
  sample_n( 2e5L, replace=TRUE, weight=value ) %>% 
  ggplot( data = .,
          aes( x=x,
               y=-y
             )
        ) +
  geom_point( alpha=0.1, size=1 ) +
  coord_fixed( ratio=1, 
               xlim = c(30, 280),
               ylim = c(-350, -20)
             ) +
  theme( plot.background = element_rect( fill ="#222222"),
         axis.text = element_text( colour = "white", size=2 ),
         panel.grid.major = element_line( colour = "grey20" ),
         axis.title = element_text(colour="white")
       ) +
  labs( x = "x",
        y = "y"
      ) +
  scale_x_continuous( breaks = seq(0, 500, 50) ) +
  scale_y_continuous( breaks = seq(0, -500, -50) )
   # saveRDS( ., 
  #             
  #        )
```

```{r fig.width=10}
load_image %>% 
  as.data.frame() %>% 
  as_tibble() %>% 
  mutate( value = 1 - ( value-min(value) ) / ( max(value)-min(value) ) ) %>% 
  sample_n( 2e4L, replace=TRUE, weight=value ) %>% 
  mutate( chars = sample(0:9, size=n(), replace=TRUE) ) %>% 
  ggplot( data = .,
          aes( x=x,
               y=-y
             )
        ) +
  geom_text( aes(label=chars), size=3, alpha=0.5 ) +
  coord_fixed( ratio=1 )
```

```{r fig.width=10}
load_image %>% 
  as.data.frame() %>% 
  as_tibble() %>%  
  mutate( value = 1 - ( value-min(value) ) / ( max(value)-min(value) ) ) %>% 
  mutate( chars = sample(0:9, size=n(), replace=TRUE) ) %>% 
  sample_n( 3e4L, replace=TRUE, weight=value ) %>% 
  ggplot( data = .,
          aes( x=x,
               y=-y
             )
        ) +
  geom_text( aes(label=chars), size=2, alpha=0.5 ) +
  coord_fixed( ratio=1 )
```

