---
title: "spectral_analysis_and_filtering"
author: "Joseph Bolton"
output: html_notebook
---

# Frequency Index parameter 

```{r}
t_seq <- seq( 0, 24, length.out=1000 )

par( mfrow=c(3,1) )

series1 <- 2 * cos( 2 * pi * (1/12) * t_seq + 0 )    # cycle every 12 time units
series2 <- 2 * cos( 2 * pi * (1/6) * t_seq + 0 )    # cycle every 6 time units
series3 <- 2 * cos( 2 * pi * (1/4) * t_seq + 0 )    # cycle every 4 time units

plot( x = t_seq,
      y = series1,
      type = "l",
      main = bquote( "A=2, "~omega*" =1/12 , "~phi*"=0" ),
      xlab = "t",
      ylab = bquote(x[t])
    )
axis( side=1, at=0:24 )

plot( x = t_seq,
      y = series2,
      type = "l",
      main = bquote( "A=2, "~omega*" =1/6 , "~phi*"=0" ),
      xlab = "t",
      ylab = expression(x[t])
    )
axis( side=1, at=0:24 )

plot( x = t_seq,
      y = series3,
      type = "l",
      main = bquote( "A=2, "~omega*" =1/4 , "~phi*"=0" ),
      xlab = "t",
      ylab = expression(x[t])
    )
axis( side=1, at=0:24 )
```

# Phase Parameter

# Height/Amplitude Parameter

# bla

The time series $y_t$ can be represented in this form:

$$y_t \quad=\quad $$

```{r echo=FALSE}
# sim series:
n <- 12
t <- 1:n
y <- cumsum( rnorm(n) )

plot( x = t,
      y = y,
      type = "b"
    )
axis( side = 1, at = 1:n )
```

```{r}
mydata <- tibble( t=t, y=y )

for( j in 1:(n/2) ){
  
  mydata[[ paste0("Xcos",j) ]] <- 
      (j/n) * cos( 2*pi*(j/n)*t )
  
    mydata[[ paste0("Xsin",j) ]] <- 
      (j/n) * sin( 2*pi*(j/n)*t )
}

fit_lm <- lm( y ~ .-t -1, data=mydata )


```

# Resources/References

* https://bookdown.org/rdpeng/timeseriesbook/frequency-and-time-scale-analysis.html

* https://online.stat.psu.edu/stat510/lesson/6/6.1
